# Generated by Django 3.1.6 on 2021-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacman_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highscore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
