# Generated by Django 3.1.6 on 2021-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacman_app', '0002_user_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
